refactor: udpate some stuff

diff --git a/lcert b/lcert
--- a/lcert
+++ b/lcert
@@ -8,8 +8,7 @@
 ### CA file to install (CUSTOMIZE!)
 ###
 
-# certfile="/etc/ssl/certs/the-spender.pem"
-# certname="The Spender CA"
+IFS="."
 
 usage() {
   echo "" 1>&2;
@@ -33,40 +32,86 @@ usage() {
   exit 1;
 }
 
-if [[ "$1" != "" ]]; then
-  certfile="$1"
-else
+load_in_trust_store() {
+  ###
+  ### For cert8 (legacy - DBM)
+  ###
+  echo "This process can take a long moment, please don't abort the task"
+  #
+  # for certDB in $(find ~/ -name "cert8.db")
+  # do
+  #     echo "cert8";
+  #     CERT_DIR=$(dirname ${certDB});
+  #     certutil -A -n "${CERT_NAME}" -t "TCu,Cu,Tu" -i ${CERT_FILE} -d dbm:${CERT_DIR}
+  # done
+  #
+  #
+  # ###
+  # ### For cert9 (SQL)
+  # ###
+  #
+  # for certDB in $(find ~/ -name "cert9.db")
+  # do
+  #     echo "cert9";
+  #     CERT_DIR=$(dirname ${certDB});
+  #     certutil -A -n "${CERT_NAME}" -t "TCu,Cu,Tu" -i ${CERT_FILE} -d sql:${CERT_DIR}
+  # done
+  echo "Loaded !"
+}
+
+while getopts "lp:n:" arg; do
+  case $arg in
+    l)
+      echo "only load cert"
+      exit 1 || return 1
+      ;;
+    p)
+      echo "path to cert ${OPTARG}"
+      CERT_PATH=${OPTARG}
+      ;;
+    n)
+      echo "name of cert ${OPTARG}"
+      CERT_NAME=${OPTARG}
+      ;;
+    *)
+      usage
+      ;;
+  esac
+done
+
+if [ -z "${CERT_PATH+x}" ] || [ -z "${CERT_NAME}" ]; then
   usage
-fi
-
-if [[ "$2" != "" ]]; then
-  certname="$2"
 else
-  certname="${certfile} CA"
+  read -p "Do you want to copy ${CERT_PATH} into /etc/ssl/certs/${CERT_NAME} [y/n]?" -n 1 -r
+  echo "" 1>&2;
+
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    read -p "Do you want to load certificate in trust store of applications [y/n]?" -n 1 -r
+    echo "" 1>&2;
+
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      [[ "$0" = "${BASH_SOURCE}" ]] && exit 1 || return 1
+    fi
+
+    CERT_FILE="/etc/ssl/certs/${CERT_NAME}"
+
+    read -ra ADDR <<< "${CERT_NAME}"
+    CERT_NAME="${ADDR[0]} CA"
+
+    load_in_trust_store
+
+    exit 1 || return 1
+  fi
+
+  # cp ${CERT_PATH} /etc/ssl/certs/
+  echo "${CERT_PATH} copied into /etc/ssl/certs/${CERT_NAME}"
+
+  CERT_FILE="/etc/ssl/certs/${CERT_NAME}"
+
+  read -ra ADDR <<< "${CERT_NAME}"
+  CERT_NAME="${ADDR[0]} CA"
+
+  load_in_trust_store
+
+  exit 1 || return 1
 fi
-
-###
-### For cert8 (legacy - DBM)
-###
-echo "This process can take a long moment, please don't abort the task"
-
-for certDB in $(find ~/ -name "cert8.db")
-do
-    echo "cert8";
-    certdir=$(dirname ${certDB});
-    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
-done
-
-
-###
-### For cert9 (SQL)
-###
-
-for certDB in $(find ~/ -name "cert9.db")
-do
-    echo "cert9";
-    certdir=$(dirname ${certDB});
-    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
-done
-
-echo "Loaded !"
